### ISSUE TITLE
[Discontinued?] For new users, there's an up to date fork to this package

### ISSUE THREAD

**Issue by micalevisk** [ericvicenti/ssh-keygen#27]
As this lib doesn't look maintained anymore, I've made a fork of it.

You can use [`ssh-keygen-lite`](https://github.com/micalevisk/ssh-keygen) as a drop-in replacement for `ssh-keygen`. It has few features, no external prod dependencies, and I've made some refactorings.

[![image](https://user-images.githubusercontent.com/13461315/153099632-da7299dc-1426-4c33-97f4-5cb249df3699.png)](https://moiva.io/?npm=@micalevisk/ssh-keygen+ssh-keygen)

(feel free to open PRs to improve the code)

**Comment by micalevisk** [comment]
### for contributors of this repo (https://github.com/ericvicenti/ssh-keygen/graphs/contributors): I could add you as a collaborator to my repo so you can publish new versions without me.

**Comment by ericvicenti** [comment]
Hi @micalevisk, sorry about the delayed response here!

If you are interested, I would be happy to add you as a maintainer of this repo and the npm package. I see you are continuing to keep your repo up-to-date.

We could also consider removing the windows binaries, because I feel uncomfortable owning opaque binaries that I did not build myself. And it may make us responsible for security patches if a vulnerability is found.

Unfortunately, we may not be allowed to publish new changes with the original name ☹️ : https://mamot.fr/@Franky47/110542776481020618
